### PR TITLE
Add empty test files to enable coverage

### PR DESCRIPTION
**Pull request by calvn**
I've added empty test files so that packages gets included as part of `go test -cover`. There was an accepted feature request regarding this on https://github.com/golang/go/issues/18909, but it looks like it won't be in until Go 1.10.

### CODE REVIEW

**Comment by rodrigo-brito** [comment]
Please, don't remove the file `config/settings_sample.yaml`. It is necessary for the tests and for settings example.

**Comment by calvn** [comment]
The `init()` func in `config.go` was panicking because it also runs on tests, so I had to rename it.

**Comment by rodrigo-brito** [comment]
On tests, the travis make a copy of ` config/settings_sample.yaml` to `config/settings.yaml`, if you are running it locally, it is necessary to make a copy too.

**Comment by calvn** [comment]
Ah, why not just use that file directly instead of copying?

**Comment by rodrigo-brito** [comment]
Beacuse, the user can use custom settings, and the git can't track that changes like passwords. That way, in the first use, the user can make a copy of the settings for personal use. It make easy to update the server without commit this changes.

**Comment by rodrigo-brito** [comment]
Hi @calvn, now the Travis show a problem in `coveralls`, I read today that the token is not needed when user with travis: https://github.com/lemurheavy/coveralls-public/issues/208#issuecomment-34496827

Please, remove `-repotoken $COVERALLS_TOKEN` from the last line.

**Comment by calvn** [comment]
Updated the travis commands to fix and actually run the tests on all packages to generate the coverprofile. Hope this helps!

**Comment by rodrigo-brito** [comment]
Great job @calvn! Happy Hacktoberfest ❤️

**Pull request merged**
